### ISSUE TITLE
after running 100% according to instructions, i just get "whoops, looks like something went wrong"

### ISSUE THREAD

**Issue by arnorhs** [nanobox-quickstarts/nanobox-laravel#8]
![image](https://user-images.githubusercontent.com/61151/31857455-a58af426-b6ce-11e7-9f93-582a2a2b45bb.png)

**Comment by danhunsaker** [comment]
What does `storage/logs/laravel.log` say? I have a suspicion but I'd like to confirm it.

**Comment by michaelGregoire** [comment]
I had the same problem, here's the error that's logged:

[2017-12-01 13:04:47] production.ERROR: RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /app/bootstrap/cache/compiled.php:13327

It looks like a .env file and app key were missing. To fix the problem all I had to do was copy the .env.example to .env and generate the key. This should probably be added to the automated script.
